/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import app.LeaderUtils.CRUDQueue;
import app.LeaderUtils.RequestAdministrator;
import app.chunk_utils.Indexer;
import app.chunk_utils.IndexFile;
import java.io.*;
import java.net.Socket;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class App {

    private static int leaderUuid = -1;
    private static volatile IndexFile ind;
    public int getLeaderUuid()
    {
        return leaderUuid;
    }
    private static final String stalker_path = "config/stalkers.list";
    private static final String harm_path = "config/stalkers.list";

    public static void main(String[] args) {
        //debugging modes: 0 - none; 1 - message only; 2 - stack traces only; 3 - stack and
        Debugger.setMode(3);
        Debugger.toggleFileMode();

        initStalker();
        ind = Indexer.loadFromFile();
        int discoveryinterval = 5;
        //starting listener thread for health check and leader election
        Thread listenerForHealth = new Thread( new ListenerThread(ind));
        listenerForHealth.start();

        //First thing to do is locate all other stalkers and print the stalkers to file
        //check the netDiscovery class to see where the file is being created
        Thread discManager = new Thread(new DiscoveryManager(Module.STALKER, discoveryinterval, false));
        discManager.start();
        boolean connected = false;
        Debugger.log("Stalker Main: This Stalker's macID" + NetworkUtils.getMacID() + "\n\n", null);
        Debugger.log("Stalker Main: Discovering nodes on network...", null);

        List<Integer> stalkerList = null;
        Map<Integer, NodeAttribute> harmlist = null;
        int attempts = 0;

        //wait for at least 2 connections
        while (!connected){
            //we will wait for network discovery to do its thing
            wait((discoveryinterval * 1000) + 5000);
            stalkerList = NetworkUtils.getStalkerList(stalker_path);
            harmlist = NetworkUtils.getNodeMap(harm_path);
            try{
                if (harmlist != null && !harmlist.isEmpty()){
                }
                else{
                    Debugger.log("Stalker Main: No HARM targets detected...", null);
                }

                if (stalkerList != null && stalkerList.size() >= 2){
                    connected = true;
                }
                else{
                    Debugger.log("Stalker Main: No STALKERs detected yet...", null);
                    Debugger.log("Stalker Main: Waiting for servers to become available...", null);
                }
            }
            catch(NullPointerException e){
                Debugger.log("", e);
            }
            attempts++;
        }
        Debugger.log("Stalker Main: System discovery complete!", null);
        int test = 0;
        //starting task for health checks on STALKERS and HARM targets
        Thread healthChecker = new Thread(new HealthChecker(Module.STALKER, null, false));
        healthChecker.start();
        //election based on networkDiscovery
        while (true){
            // Leader election by asking for a leader
            LeaderCheck leaderchecker = new LeaderCheck();
            leaderchecker.election();
            leaderUuid = LeaderCheck.getLeaderUuid();

            int role = ElectionUtils.identifyRole(stalkerList,leaderUuid);
            if (role != 0){
                getConfirmation(leaderUuid);
            }
            switch (role){
                case 0:
                    Debugger.log("<<<<<<<-----Leader Online----->>>>>>> \n\n", null);
                    //This means that this STK is the leader
                    //create a priority comparator for the Priority queue
                    CRUDQueue syncQueue = new CRUDQueue();
                    Thread t1 = new Thread(new StalkerRequestHandler(syncQueue));
                    Thread t2 =  new Thread(new RequestAdministrator(syncQueue));
                    t1.start();
                    t2.start();

                    try{
                        t1.join();
                        t2.join();
                    }
                    catch(InterruptedException e){
                        Debugger.log("", e);
                    }
                    break;
                case 1:
                    Debugger.log("<<<<<<<-----Worker Online----->>>>>>>\n\n", null);
                    Thread jcpReq = new Thread(new JcpRequestHandler(ind));
//                JcpRequestHandler jcpRequestHandler = new JcpRequestHandler(ind);
//                jcpRequestHandler.run();
                    jcpReq.start();
                    try {
                        jcpReq.join();
                    }
                    catch(InterruptedException e){
                        Debugger.log("", e);
                    }
                    break;
                case 2:
                    Debugger.log("<<<<<<<-----Vice Leader Online----->>>>>>>\n\n", null);
                    Thread vice = new Thread(new JcpRequestHandler(ind));
//                JcpRequestHandler jcpRequestHandler = new JcpRequestHandler(ind);
//                jcpRequestHandler.run();
                    vice.start();
                    try {
                        vice.join();
                    }
                    catch(InterruptedException e){
                        Debugger.log("", e);
                    }
                    break;
            }
        }

    }

    public static void initStalker(){
        List<File> directories = new ArrayList<>();
        directories.add(new File("temp"));
        directories.add(new File("logs"));
        directories.add(new File("index"));
        directories.add(new File("config"));
        directories.add(new File("temp/chunks"));
        directories.add(new File("temp/toChunk"));
        directories.add(new File("temp/reassembled"));
        NetworkUtils.initDirs(directories, true, 3);
    }
    //will block worker from doing anythin until the leader is confirmed
    public static void getConfirmation(int uuid) {
        CommsHandler commLink = new CommsHandler();
        boolean success = false;
        while (!success) {
            try {
                Socket leader = NetworkUtils.createConnection(NetworkUtils.getStalkerMap(stalker_path).get(uuid), 11112);
                if (leader != null) {
                    if (commLink.sendPacket(leader, MessageType.CONFIRM, "", true) == MessageType.CONFIRM) {
                        success = true;
                        Debugger.log("Leader has granted permission to start!", null);
                    }
                } else {
                    wait(5000);
                }
            } catch (IOException e) {
                wait(5000);
                Debugger.log("", e);
            }

        }
    }

    public static void wait(int millis){
        try{
            //wait for a bit
            Thread.sleep((long)((millis)));
        }
        catch (InterruptedException ex){
            Debugger.log("", ex);
        }
    }



}

