/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

public class FileChunker {
    private String greet;

    public FileChunker() {
        greet = "hello";
    }


    public void printGreet(){
        System.out.println(greet);
    }


}
