/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        if (args.length > 0){
            System.out.println("Harm " + args[0] + " running!");
        }
    }
}
